#%RAML 1.0 ResourceType
description: Collection GET
get:
  is:
    - errorResponses
  responses:
    200:
      description: Successful retrieval
      body:
        application/json:
          examples:
            success: !include ../examples/records.json
