#%RAML 1.0
title: exp-sat-datashare-api-prod
version: v1
protocols: [ HTTPS ]
baseUri: https://api.example.com/exp-sat-datashare-api-prod
mediaType: application/json

uses:
  types: libraries/types.raml

resourceTypes:
  collection: !include resourceTypes/collection.raml

/v1/invoicing:
  type: { collection: { responseType: types.InvoiceCollection, queryTrait: invoicingQuery } }

/v1/ordering:
  type: { collection: { responseType: types.OrderCollection, queryTrait: orderingQuery } }

/v1/products:
  type: { collection: { responseType: types.ProductCollection, queryTrait: productsQuery } }

/v1/routes:
  type: { collection: { responseType: types.RouteCollection, queryTrait: routesQuery } }

/v1/salesreps:
  type: { collection: { responseType: types.SalesRepCollection, queryTrait: salesrepsQuery } }

/v1/stores:
  type: { collection: { responseType: types.StoreCollection, queryTrait: storesQuery } }

/v1/inventory:
  type: { collection: { responseType: types.InventoryCollection, queryTrait: inventoryQuery } }

/v1/warehouses:
  type: { collection: { responseType: types.WarehouseCollection, queryTrait: warehousesQuery } }
