#%RAML 1.0
title: exp-sat-datashare-api-prod
version: v1
protocols: [ HTTPS ]
baseUri: https://api.example.com/exp-sat-datashare-api-prod
mediaType: application/json

uses:
  types: libraries/types.raml

traits:
  queryParams: !include traits/query-params.raml
  errorResponses: !include traits/error-responses.raml

resourceTypes:
  collection: !include resourceTypes/collection.raml

/v1/invoicing:
  type: { collection: { responseType: types.InvoiceCollection, example: !include examples/invoicing.json } }

/v1/ordering:
  type: { collection: { responseType: types.OrderCollection, example: !include examples/ordering.json } }

/v1/products:
  type: { collection: { responseType: types.ProductCollection, example: !include examples/products.json } }

/v1/routes:
  type: { collection: { responseType: types.RouteCollection, example: !include examples/routes.json } }

/v1/salesreps:
  type: { collection: { responseType: types.SalesRepCollection, example: !include examples/salesreps.json } }

/v1/stores:
  type: { collection: { responseType: types.StoreCollection, example: !include examples/stores.json } }

/v1/inventory:
  type: { collection: { responseType: types.InventoryCollection, example: !include examples/inventory.json } }

/v1/warehouses:
  type: { collection: { responseType: types.WarehouseCollection, example: !include examples/warehouses.json } }
