#%RAML 1.0
title: exp-sat-datashare-api-prod
version: v1
protocols: [ HTTPS ]
baseUri: https://api.example.com/exp-sat-datashare-api-prod
mediaType: application/json

uses:
  types: libraries/types.raml

resourceTypes:
  invoice: !include resourceTypes/invoice.raml
  order: !include resourceTypes/order.raml
  product: !include resourceTypes/product.raml
  route: !include resourceTypes/route.raml
  salesRep: !include resourceTypes/salesrep.raml
  store: !include resourceTypes/store.raml
  inventory: !include resourceTypes/inventory.raml
  warehouse: !include resourceTypes/warehouse.raml

/v1/Invoice:
  type: invoice

/v1/Order:
  type: order

/v1/Product:
  type: product

/v1/Route:
  type: route

/v1/SalesRep:
  type: salesRep

/v1/Store:
  type: store

/v1/Inventory:
  type: inventory

/v1/Warehouse:
  type: warehouse
