#HTTP Request
http.request.retry.count =1
http.request.retry.interval =1000
#HTTP Listener
http.listener.host = 0.0.0.0
http.listener.port = 8081
http.request.response.timeout = 90000

# Experience API public host used in next URLs
eapi.host = https://exp-sat-datashare-sand-api-5nct48.2ky31l-2.deu-c1.eu1.cloudhub.io

# Process API
process.api.host = prc-solutech-api-v1-5nct48.2ky31l-1.deu-c1.eu1.cloudhub.io
process.api.port = 443
process.api.basePath = /api
