#%RAML 1.0 ResourceType
usage: Collection GET. Applies the named query trait and shared errors from libraries/traits.raml.

uses:
  t: ../libraries/traits.raml

description: Collection of <<resourcePathName>>
get:
  displayName: Get <<resourcePathName>>
  description: Retrieve <<resourcePathName>> for the given date range.
  is:
    - t.<<queryTrait>>
    - t.errorResponses
  responses:
    200:
      description: Successful retrieval of <<resourcePathName>>
      body:
        application/json:
          type: <<responseType>>
          examples:
            success: !include ../examples/records.json
