#%RAML 1.0 ResourceType
usage: Collection GET resource used by all SAT Datashare list endpoints

description: Collection of <<resourcePathName>>
get:
  displayName: Get <<resourcePathName>>
  description: Retrieve <<resourcePathName>> for the given date range.
  is:
    - errorResponses
  responses:
    200:
      description: Successful retrieval of <<resourcePathName>>
      body:
        application/json:
          type: <<responseType>>
          examples:
            success: <<example>>
