#%RAML 1.0 ResourceType
usage: Collection GET resource used by all SAT Datashare list endpoints

description: Collection of <<resourcePathName>>
get:
  displayName: Get <<resourcePathName>>
  description: Retrieve a paginated list of <<resourcePathName>> for the given date range. Optional product filters may be applied. Query parameters are shared today and can be specialized per resource later.
  is:
    - queryParams
    - errorResponses
  responses:
    200:
      description: Successful retrieval of <<resourcePathName>>
      body:
        application/json:
          type: <<responseType>>
          examples:
            success: <<example>>
