#%RAML 1.0 ResourceType
uses:
  t: ../libraries/traits.raml
  types: ../libraries/types.raml

description: Warehouse collection
get:
  displayName: Get Warehouse
  description: Retrieve Warehouse records for the given date range.
  is:
    - t.warehouseQuery
    - t.errorResponses
  responses:
    200:
      description: Successful retrieval of Warehouse records
      body:
        application/json:
          type: types.WarehouseCollection
          examples:
            success: !include ../examples/records.json
