#%RAML 1.0 Library
usage: Query-parameter and error traits. Applied from resource types, not from the root RAML.

traits:
  invoiceQuery: !include ../traits/invoice-query.raml
  orderQuery: !include ../traits/order-query.raml
  productQuery: !include ../traits/product-query.raml
  routeQuery: !include ../traits/route-query.raml
  salesRepQuery: !include ../traits/salesrep-query.raml
  storeQuery: !include ../traits/store-query.raml
  inventoryQuery: !include ../traits/inventory-query.raml
  warehouseQuery: !include ../traits/warehouse-query.raml
  errorResponses: !include ../traits/error-responses.raml
