#%RAML 1.0 Library
usage: Query-parameter and error traits. Applied from resource types, not from the root RAML.

traits:
  invoicingQuery: !include ../traits/invoicing-query.raml
  orderingQuery: !include ../traits/ordering-query.raml
  productsQuery: !include ../traits/products-query.raml
  routesQuery: !include ../traits/routes-query.raml
  salesrepsQuery: !include ../traits/salesreps-query.raml
  storesQuery: !include ../traits/stores-query.raml
  inventoryQuery: !include ../traits/inventory-query.raml
  warehousesQuery: !include ../traits/warehouses-query.raml
  errorResponses: !include ../traits/error-responses.raml
