#%RAML 1.0 Library
usage: Shared data types for SAT Datashare Experience API

types:
  ErrorDetail:
    type: object
    additionalProperties: false
    properties:
      code:
        type: string
        example: BAD_REQUEST
      message:
        type: string
        example: Invalid query parameter value
      correlationId:
        type: string
        example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
      timestamp:
        type: datetime
        example: 2026-08-13T17:00:00.000Z
      details:
        type: string
        required: false

  ErrorResponse:
    type: object
    additionalProperties: false
    properties:
      error: ErrorDetail

  DataShareRecord:
    type: object
    additionalProperties: false
    properties:
      RECORDID:
        type: integer
        example: 1
      USERID:
        type: integer
        example: 2
      USERNAME:
        type: string
        example: TEST ACCOUNT
      SHOPID:
        type: integer
        example: 185
      CUSTOMERNAME:
        type: string
        example: NEW CUSTOMER
      CUSTOMERCATEGORY:
        type: string
        example: RETAIL SHOP
      LOCATION_NAME:
        type: string
        example: GIKAMBURA
      LOCATION_ID:
        type: integer
        example: 4
      ACCOUNTNAME:
        type: nil | string
        example: null
      USERCATEGORY:
        type: string
        example: SOLUTECH
      REGION_NAME:
        type: string
        example: NAIROBI
      PRODUCTCATEGORY:
        type: nil | string
        example: null
      BRAND_NAME:
        type: string
        example: LIGHTERS
      CSKU:
        type: nil | string
        example: null
      MECHANISM:
        type: string
        example: BOGOF
      BEFOREVALUE:
        type: string
        example: "300"
      AFTERVALUE:
        type: string
        example: "250"
      NOTES:
        type: string
        example: test
      ENTRYTIME:
        type: string
        example: "2026-06-08T16:28:55"
      CREATED_AT:
        type: string
        example: "2026-06-08T16:28:57"
      UPDATED_AT:
        type: string
        example: "2026-06-08T16:28:57"

  InvoiceCollection: DataShareRecord[]
  OrderCollection: DataShareRecord[]
  ProductCollection: DataShareRecord[]
  RouteCollection: DataShareRecord[]
  SalesRepCollection: DataShareRecord[]
  StoreCollection: DataShareRecord[]
  InventoryCollection: DataShareRecord[]
  WarehouseCollection: DataShareRecord[]
