#%RAML 1.0 Library
usage: Shared error types for SAT Datashare Experience API

types:
  ErrorDetail:
    type: object
    additionalProperties: false
    properties:
      code:
        type: string
        example: BAD_REQUEST
      message:
        type: string
        example: Invalid query parameter value
      correlationId:
        type: string
        example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
      timestamp:
        type: datetime
        example: 2026-08-13T17:00:00.000Z
      details:
        type: string
        required: false

  ErrorResponse:
    type: object
    additionalProperties: false
    properties:
      error: ErrorDetail
