#HTTP Request
http.request.retry.count =1
http.request.retry.interval =1000
#HTTP Listener
http.listener.host = 0.0.0.0
http.listener.port = 8081
#40 minutes
http.request.response.timeout = 2400000
#500MB
http.request.inMemorySize = 500
#solutechlabs
erp.solutechlabs.api = sgug.solutechlabs.com
erp.solutechlabs.grant_type = client_credentials
erp.solutechlabs.client_id = 9
erp.solutechlabs.scope = *
erp.solutechlabs.provider = Users
erp.solutechlabs.client_secret=![lBRu9fnd9FvFbK1zfrkgCy7aCQ0z2twMW4vnqmchxRdqvwPg8R6Tlkbr21woDdRj]
truststore.password =![4Sm5doiOve8kWs7WfTBMGw==]






