traits:
  bearerAuth: !include traits/trait-bearerAuth.raml
  queryp_Customers: !include traits/trait-CustomersQueryparams.raml
  queryp_Invoice: !include traits/trait-Adapter_InvoiceQueryparams.raml
  queryp_Order: !include traits/trait-Adapter_OrderQueryparams.raml
  queryp_Product: !include traits/trait-Adapter_ProductQueryparams.raml
  queryp_Route: !include traits/trait-Adapter_RouteQueryparams.raml
  queryp_SalesRep: !include traits/trait-Adapter_SalesRepQueryparams.raml
  queryp_Customer: !include traits/trait-Adapter_CustomerQueryparams.raml
  queryp_Stock: !include traits/trait-Adapter_StockQueryparams.raml
  queryp_Warehouse: !include traits/trait-Adapter_WarehouseQueryparams.raml
