#%RAML 1.0 Trait
usage: Query parameters for GET /v1/Store

queryParameters:
  fromDate:
    type: string
    required: true
    description: Inclusive start date (YYYY-MM-DD)
    example: "2026-08-01"
  toDate:
    type: string
    required: true
    description: Inclusive end date (YYYY-MM-DD)
    example: "2026-08-10"
  PageNumber:
    type: string
    required: false
    default: "1"
    description: Page number
    example: "1"
