#HTTP Request
http.request.retry.count =5
http.request.retry.interval =6000
#HTTP Listener
http.listener.host = 0.0.0.0
http.listener.port = 8081
#40 minutes
http.request.response.timeout = 2400000
#500MB
http.request.inMemorySize = 500
#sys.solutech
sys.solutech.api = sys-solutech-api-v1-5nct48.2ky31l-2.deu-c1.eu1.cloudhub.io
sys.solutech.adapter.invoice.path = /api/Adapter_Invoice
sys.solutech.product.path = /api/v1/integrations/products
sys.solutech.sale.path = /api/v1/integrations/sales
sys.solutech.access_token = test
business.central.process.api = prc-erp-api-v7-5nct48.2ky31l-2.deu-c1.eu1.cloudhub.io

#oauth2
microsoftonline.oauth2.token=login.microsoftonline.com
microsoftonline.oauth2.grant_type = client_credentials
microsoftonline.oauth2.client_id = 10
microsoftonline.oauth2.scope = https://graph.microsoft.com/.default
microsoftonline.oauth2.client_secret=![sYOssOnHpzEXETWwM0aqguBxqkTL2FVKhDK+UepBxuNqPHqLUh/LictaedAQgNX8]

