#HTTP Request
http.request.retry.count =1
http.request.retry.interval =1000
#HTTP Listener
http.listener.host = 0.0.0.0
http.listener.port = 8081
#40 minutes
http.request.response.timeout = 2400000
#500MB
http.request.inMemorySize = 500
#solutechlabs
erp.solutechlabs.domain=solutechlabs.com
truststore.password =![4Sm5doiOve8kWs7WfTBMGw==]
mapping.sgug.name = SAT_SGUG_PROD
mapping.sgug.grant_type = client_credentials
mapping.sgug.client_id = 9
mapping.sgug.scope = *
mapping.sgug.provider = Users
mapping.sgug.client_secret=![lBRu9fnd9FvFbK1zfrkgCy7aCQ0z2twMW4vnqmchxRdqvwPg8R6Tlkbr21woDdRj]

mapping.sguat.name = SAT_SGMALT_UAT
mapping.sguat.grant_type = client_credentials
mapping.sguat.client_id = 019ef912-fffe-732f-b27e-b9d512cb798e
mapping.sguat.scope = *
mapping.sguat.provider = Users
mapping.sguat.client_secret=![yLQlNxua4MOLAN4TUzfGaUb2FIOUQ64uWyb3yYFQiXkNhJgs5w17L9g7fxaZTxLO]

# MySQL SAT BI
db.host=167.99.57.12
db.port=1166
db.user=sat_salvogrima_bi
db.password=YPQmESeDMgs@q2iYYxQ)5202!
db.name=sat_nobleoutlook
db.page.size=100
db.table.sales=bi_salesmaster
db.table.visits=bi_customer_visits
db.table.products=bi_products







